# ===============================
#   SERVER CONFIGURATION
# ===============================
server:
  port: 8081

spring:
  # ===============================
  #   DATABASE CONFIGURATION
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: authuser
    password: Authp@ss
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ===============================
  #   JPA CONFIGURATION
  # ===============================
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  # ===============================
  #   REDIS
  # ===============================
  redis:
    host: localhost
    port: 6379
